### ISSUE TITLE
Can't install on Node.js 16+

### ISSUE THREAD

**Issue by lcswillems** [ElrondNetwork/dapp-template#15]
Hi,

The template includes the version 4.14.1 of package `node-sass`. This version is not compatible with Node.js 16+:

![Screenshot_20210916_165557](https://user-images.githubusercontent.com/5437552/133635240-394903f1-a1d9-4f8d-b01b-d72505f4d420.png)

Moreover, this package is deprecated. So maybe stopping using it would be the best thing to do.

For people facing this issue, upgrading the package to the latest version should fix it.

**Comment by bogdan-marian** [comment]
I was able to get past this error by downgrading from `node14` to `node12`. On my Ubuntu system, I have node installed via `brew`. This is how I downgraded.  
```
brew install node@12
brew unlink node
brew link --overwrite node@12
```

**Comment by StanislavSava** [comment]
This issue has been fixed with the latest releases.
