### ISSUE TITLE
`config` file not found

### ISSUE THREAD

**Issue by lcswillems** [ElrondNetwork/dapp-template#16]
When executing `npm install` and then `npm run start`, I get multiple errors saying the `config` file is not found. In fact, it is named `config.devnet.ts`.

I think the file should be renamed to `config.ts` to make the installation smooth. People will then rename it they want to handle multiple chains.

**Comment by Galudas** [comment]
I have the same issue and I tried to install it, but then none of the used components are found any more.

**Comment by StanislavSava** [comment]
duplicate of https://github.com/ElrondNetwork/dapp-template/issues/41
