### ISSUE TITLE
Is there a way to set the necessary permissions for walletConnect ?

### ISSUE THREAD

**Issue by Axel77g** [ElrondNetwork/dapp-template#17]
### Hi everyone !
I would like to know if there was a way to set the permissions needed to connect, indeed when connecting with Maiar App asks for a permission named :

> request approval for transactions 

I would just like to remove this permission :)

Thank you for this superb template!
Have nice day

**Comment by StanislavSava** [comment]
Nope, there is no way to change the permissions, these are the default ones needed  for the app to functionn
