### ISSUE TITLE
creating dapp without legacy deps

### ISSUE THREAD

**Issue by juliencrn** [ElrondNetwork/dapp-template#20]
I'm feeling forced to use create-react-app with bootstrap, node-sass, moment, node 14 etc. to create an Elrong dapp, it's a bit frustrating . 
Moreover, I wanted to have access, by example, to the "unlock" page to personalize it. 

How can I create an Elrond dapp using the technologies I want (e.g. Next.js, Tailwind) with full access to the frontend? 

Could you publish your @elrondnetwork/dapp in open source to let the community helping to do the work.

**Comment by coldiary** [comment]
@elrondnetwork/dapp is open-source, you can find it here : https://github.com/ElrondNetwork/dapp
But it's still opinionated, so it's not a solution. I hope we'll see better developper tooling to use in any framework we like.

**Comment by dnnaji** [comment]
I think the improvement is dropping soon: https://github.com/ElrondNetwork/dapp-template/pull/21

@LucianMincu is this correct?

**Comment by LucianMincu** [comment]
@dnnaji indeed! 

@constantintovisi @arhtudormorar do we have any ETA for [this](https://github.com/ElrondNetwork/dapp-template/pull/21) PR?

**Comment by arhtudormorar** [comment]
The latest [PR](https://github.com/ElrondNetwork/dapp-template/pull/21) is live and allows more customisation. Check out [dapp-core](https://github.com/ElrondNetwork/dapp-core) to see the options

**Comment by juliencrn** [comment]
Great! Thanks 👍

However, @arhtudormorar [dapp-core](https://github.com/ElrondNetwork/dapp-core) is in 404 for me, it's a private repo?

**Comment by dnnaji** [comment]
Yes, @juliencrn, the repo is still private.

@arhtudormorar , fyi.

**Comment by LucianMincu** [comment]
Hey @dnnaji @juliencrn! 

Awesome news!

https://github.com/ElrondNetwork/dapp-core is now public. 🔥

**Comment by dnnaji** [comment]
Thanks, @LucianMincu. Time to get my hands dirty now. 😁
