### ISSUE TITLE
WalletConnect not working

### ISSUE THREAD

**Issue by ethwork** [ElrondNetwork/dapp-template#28]
When trying to connect with the Maiar app using WalletConnect, I get the following error:

`WebSocket connection to 'wss://walletconnect-bridge.maiar.com/?env=browser&host=localhost%3A3000&protocol=wc&version=1' failed: `

This is not just my local machine, the same error is present in the [deployed example app too](https://dapp-template.elrond.com/)

Just click login and select Maiar to reproduce.

Any ideas what is wrong?

**Comment by radumojic** [comment]
Fixed in PR #29
