### ISSUE TITLE
Sending transactions don't work with Maiar app

### ISSUE THREAD

**Issue by ethwork** [ElrondNetwork/dapp-template#31]
When trying to send a transaction after connecting with Maiar, a popup opens telling me to confirm on Maiar. However, nothing happens in the app itself, and therefore the transaction cannot be sent.

Reproduce:

1) go to [example app](https://dapp-template.elrond.com/unlock)
2) login with Maiar
3) click Ping (or Pong)

**Comment by StanislavSava** [comment]
This seems like an old issue that has been solved. I'll close the issue, but please feel free to reopen if it still persists.
