### ISSUE TITLE
Module not found: Can't resolve 'config' in 'dapp-template/src'

### ISSUE THREAD

**Issue by bogdan-marian** [ElrondNetwork/dapp-template#41]
Cloning and running this project you get the following error
```
Failed to compile.

./src/App.tsx
Module not found: Can't resolve 'config' in '/home/bogdan/workspace/dapp-template/src'
```

How to reproduce:
```bash
npm install
npm run start
```

**Comment by CristianFodor** [comment]
You have to create manually a file named config.tsx and add your params. Be careful if you have a file config.devnet.tsx when you are going to run `npm run start-devnet` the config.tsx file will be overwritten.

More info you can find in the scripts area from package.json.

**Comment by bogdan-marian** [comment]
@CristianFodor Hello Cristian
Thank you for your help. My problem is solved. My report should still be considered valid. The instructions from the readme are misleading. I would help a lot of the new developers if we would replace the `npm run start` section with 
```bash
npm run start-devnet
```
Also pointing out the fact that this will generate the `src/config.tsx` file helped a lot. (That is missing also from the readme)

**Comment by CristianFodor** [comment]
Hello again, 

After the yesterday release the config.tsx file was removed from gitignore and was added to the template. So there will be no more errors at the moment of building the app regarding the missing config.tsx file. But you have to be careful not to store sensitive data in config.tsx anymore.

**Comment by StanislavSava** [comment]
In the latest dapp-core versions, config is no longer stored here. You can override the default config with a custom one, but that is an advanced usage.
