### ISSUE TITLE
"Network change detected The application tried to change  the transaction network" error 

### ISSUE THREAD

**Issue by uluckpt** [ElrondNetwork/dapp-template#49]
hi,
i am playing with dapp-template and enviorement is as "const environment = 'devnet'" in App.tsx file.
I have a query with sc and it is working as expected. But receiving "Network change detected The application tried to change the transaction network" error   when i add sc call method in order to interact with sc,

i checked chain ID with console.log(NetworkConfig.getDefault().ChainID) and it seems as 'T',i think it should be 'D' and it is causing the error. Why the chainID is  'T'  while enviroment set as devnet ??

note : i added   "await NetworkConfig.getDefault().sync(proxy) " into sc call function in order to solve problem.

// ectractted from my code

    const { network } = useGetNetworkConfig();
    const proxy = new ProxyProvider(network.apiAddress);
    const contract = new SmartContract({ address: new Address(contractAddress) });
  
    const sendBuyTransaction = async () => {
    await NetworkConfig.getDefault().sync(proxy);
     const buyTransaction = contract.call({
        args: [BytesValue.fromUTF8('scFunctionArgument')],
        func: new ContractFunction('scFunction'),
        gasLimit: new GasLimit(5000000),
        receiver: new Address(contractAddress),
        value: Balance .egld(0.1)
    });
   await refreshAccount();

    const { sessionId /*, error*/ } = await sendTransactions({
      transactions: buyTransaction,
      transactionsDisplayInfo: {
        processingMessage: 'Processing Buy transaction',
        errorMessage: 'An error has occured during transaction',
        successMessage: 'Good to go'
      },
      redirectAfterSign: false,
      callbackRoute: '/dashboard'
    });
    console.log(sessionId);
    if (sessionId != null) {
      setTransactionSessionId(sessionId);
    }
  };

**Comment by StanislavSava** [comment]
It seems that the transaction you're trying to send has "T" as the chainId, and this might be causing the issue. Can you check if you're changing the chainid before sending the transaction to be signed?

**Comment by CiprianDraghici** [comment]
Closed due to inactivity
