### ISSUE TITLE
Feedback / questions after using dapp template for hackathon

### ISSUE THREAD

**Issue by rootulp** [ElrondNetwork/dapp-template#7]
Hi Elrond team! Thank you for creating this dapp-template. I have some feedback / questions after using this template for a hackathon. I'm happy to create a PR for any of the feedback listed below if maintainers of this project are open to the change.

## Feedback
1. Extract UI visible "Dapp" to a string constant that can be changed in one location. This will make it easier to re-brand the template for a particular app name.
2. Rename "Close" => "Log out"
3. Enable [prettier](https://prettier.io/)
4. Enable [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin)
5. Include an example smart contract query in the dapp template (i.e. call `balanceOf` on an ERC20 compliant smart contract deployed to Elrond)
6. Add a prop to the `Denominate` component to support showing the label of tokens that aren't just `egldLabel`. This would make the component usable for ESDT / ERC20 tokens.
7. Convert `.jsx` files to `.tsx` files (i.e. Layout/Footer/index.jsx)

## Questions
1. Is there a conversion utility available to convert a base64 encoded string to a number? When I query a smart contract (i.e. get the token balance of an Elrond deployed ERC20 smart contract), I get back a result that contains the value in a base64 encoded string. I have to decode the string using a util method from `protobuf` and then convert a big endian array into a numeric value. Code sample [here](https://gist.github.com/rootulp/05652d58dbea00a4e4857284b63af036). Is there a better way to do this? 
2. I found it tricky to navigate the file structure for components of this app. Would maintainers be open to the idea of having one `/components` directory with a flat list of files for components? This also implies moving components from `/pages` to `/components`.
3. `index.tsx` as the file name for components makes it difficult to Cmd + P for the file you're looking for. Are maintainers open to renaming `index.tsx` to component names (i.e. `Footer.tsx`). I think one root level `src/index.tsx` should be preserved.
4. Can maintainers include in the README a brief description on `Dapp.useContext()` vs. `useContext()` (imported from context in this project) vs. `React.useContext()`

**Comment by arhtudormorar** [comment]
Hi!
  I will try to respond point by point to your suggestions:

Feedback:

1. Will be implemented in the next release
2. It's a matter of preference for the developer
3. Can be set up in VsCode and will work
4. EsLint can be set up in VsCode and will work
5. It's beside the purpose of the dapp template for now
6. Will be implemented in the next release
7. Will be implemented in the next release

Questions

1. Please try the telegram support channel for this
2. The project follows a standard architecture scheme. It can be changed by the developer since it's not a large project
3. Same as point 3
4. Depending on the source of the import, you gain access to different properties (ex: Dapp.context offers information about the logged in account) 

  Thanks for your feedback!

**Comment by rootulp** [comment]
> It's a matter of preference for the developer

I don't know of any web apps that renamed "Log out" to "Close". I don't think it's a preference for the developer. I think "Log out" is the canonical term used for logging out of a web app. "Close" represents something different (i.e. close this tab).

> EsLint is included by default by Create React App. Enabling the extension in VS Code should make it work

No it won't. This is in reference to extending another set of rules [here](https://github.com/ElrondNetwork/dapp-template/blob/master/package.json#L38-L41)

> Depending on the source of the import, you gain access to different properties (ex: Dapp.context offers information about the logged in account)

This doesn't clear up my confusion on when to use which type of context. I still think a README section on different contexts would be helpful.
